import type { CommandDefinition } from '@shared/types'

export const COMMAND_DEFINITIONS: CommandDefinition[] = [
  { name: 'copy', description: 'Copy files from source to dest, skipping identical files', category: 'Transfer', usesSource: true, usesDestination: true, commonFlags: ['transfers', 'checkers', 'bwlimit', 'dry-run', 'progress', 'verbose'], advancedFlags: ['fast-list', 'checksum', 'ignore-existing', 'size-only'] },
  { name: 'sync', description: 'Make source and dest identical, modifying destination only', category: 'Transfer', usesSource: true, usesDestination: true, commonFlags: ['transfers', 'checkers', 'bwlimit', 'dry-run', 'progress', 'verbose', 'delete-before', 'delete-during', 'delete-after'], advancedFlags: ['backup-dir', 'track-renames', 'suffix'] },
  { name: 'move', description: 'Move files from source to dest', category: 'Transfer', usesSource: true, usesDestination: true, commonFlags: ['transfers', 'checkers', 'bwlimit', 'dry-run', 'progress', 'verbose'], advancedFlags: ['delete-empty-src-dirs'] },
  { name: 'bisync', description: 'Bidirectional synchronization between two paths', category: 'Transfer', usesSource: true, usesDestination: true, commonFlags: ['dry-run', 'verbose'], advancedFlags: ['force', 'resync'] },
  { name: 'copyto', description: 'Copy files from source to dest (allows renaming)', category: 'Transfer', usesSource: true, usesDestination: true, commonFlags: ['transfers', 'dry-run'], advancedFlags: [] },
  { name: 'moveto', description: 'Move file or directory from source to dest', category: 'Transfer', usesSource: true, usesDestination: true, commonFlags: ['dry-run'], advancedFlags: [] },
  { name: 'check', description: 'Checks the files in source and destination match', category: 'Verification', usesSource: true, usesDestination: true, commonFlags: ['verbose'], advancedFlags: ['one-way', 'download'] },
  { name: 'ls', description: 'List the objects in the path with size and path', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: ['max-depth', 'long-listing'], advancedFlags: [] },
  { name: 'lsl', description: 'List the objects with modification time, size and path', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: ['max-depth'], advancedFlags: [] },
  { name: 'lsf', description: 'List directories and objects formatted for parsing', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: ['format', 'delimiter', 'max-depth'], advancedFlags: ['quote', 'no-mimetype'] },
  { name: 'lsjson', description: 'List directories and objects in JSON format', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: ['max-depth'], advancedFlags: ['no-mimetype', 'no-modtime', 'hash-type'] },
  { name: 'lsd', description: 'List all directories/containers/buckets in the path', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: ['max-depth'], advancedFlags: [] },
  { name: 'size', description: 'Print the total size and number of objects in remote:path', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'mkdir', description: 'Make the path if it doesn\'t already exist', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'rmdir', description: 'Remove the empty directory at path', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'rmdirs', description: 'Remove empty directories under the path', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: ['stop-at-remove'] },
  { name: 'purge', description: 'Remove the path and all of its contents', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: ['dry-run'], advancedFlags: [] },
  { name: 'delete', description: 'Remove the files in path', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: ['dry-run', 'verbose'], advancedFlags: [] },
  { name: 'deletefile', description: 'Remove a single file from remote', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: ['dry-run'], advancedFlags: [] },
  { name: 'cleanup', description: 'Clean up the remote if possible', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: ['verbose'], advancedFlags: [] },
  { name: 'dedupe', description: 'Interactively find duplicate filenames and delete/rename them', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: ['dry-run'], advancedFlags: ['dedupe-mode'] },
  { name: 'about', description: 'Get quota information from the remote', category: 'Information', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'cat', description: 'Concatenate any files and send them to stdout', category: 'Transfer', usesSource: true, usesDestination: false, commonFlags: ['offset', 'count'], advancedFlags: [] },
  { name: 'copyurl', description: 'Copy the contents of a URL to dest:path', category: 'Transfer', usesSource: false, usesDestination: true, commonFlags: ['auto-filename', 'no-head', 'no-traverse'], advancedFlags: [] },
  { name: 'touch', description: 'Create new file or change file modification time', category: 'Operations', usesSource: true, usesDestination: false, commonFlags: ['timestamp'], advancedFlags: [] },
  { name: 'tree', description: 'List the contents of the remote in a tree-like fashion', category: 'Listing', usesSource: true, usesDestination: false, commonFlags: ['max-depth'], advancedFlags: [] },
  { name: 'hashsum', description: 'Produces a hashsum file for all objects in the path', category: 'Verification', usesSource: true, usesDestination: false, commonFlags: ['hash'], advancedFlags: [] },
  { name: 'cryptcheck', description: 'Check the integrity of an encrypted remote', category: 'Verification', usesSource: true, usesDestination: true, commonFlags: [], advancedFlags: [] },
  { name: 'cryptdecode', description: 'Returns unencrypted file names from a crypt remote', category: 'Information', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'link', description: 'Generate public link to file/folder', category: 'Information', usesSource: true, usesDestination: false, commonFlags: ['expires', 'unlink'], advancedFlags: [] },
  { name: 'listremotes', description: 'List all the remotes in the config file', category: 'Information', usesSource: false, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'obscure', description: 'Obscure password for use in the rclone config file', category: 'Information', usesSource: false, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'version', description: 'Show the version number', category: 'Information', usesSource: false, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'selfupdate', description: 'Update the rclone binary', category: 'Information', usesSource: false, usesDestination: false, commonFlags: ['stable', 'beta'], advancedFlags: [] },
  { name: 'mount', description: 'Mount the remote as file system on a mountpoint (FUSE)', category: 'Mount', usesSource: true, usesDestination: false, commonFlags: ['allow-other', 'allow-non-empty', 'vfs-cache-mode', 'daemon'], advancedFlags: ['poll-interval', 'buffer-size', 'dir-cache', 'vfs-cache-max-age', 'vfs-cache-max-size'] },
  { name: 'nfsmount', description: 'Mount the remote as NFS file system', category: 'Mount', usesSource: true, usesDestination: false, commonFlags: ['daemon'], advancedFlags: [] },
  { name: 'serve', description: 'Serve a remote over a protocol', category: 'Server', usesSource: true, usesDestination: false, commonFlags: ['addr', 'port'], advancedFlags: [] },
  { name: 'rc', description: 'Run a command against a running rclone', category: 'Advanced', usesSource: false, usesDestination: false, commonFlags: ['url', 'user', 'pass'], advancedFlags: [] },
  { name: 'config', description: 'Enter an interactive configuration session', category: 'Advanced', usesSource: false, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'backend', description: 'Run a backend-specific command', category: 'Advanced', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'ncdu', description: 'Explore a remote with a text based user interface', category: 'Information', usesSource: true, usesDestination: false, commonFlags: [], advancedFlags: [] },
  { name: 'genautocomplete', description: 'Output completion script for shell', category: 'Advanced', usesSource: false, usesDestination: false, commonFlags: [], advancedFlags: [] }
]
