import type { FlagDefinition } from '@shared/types'

export const FLAG_DEFINITIONS: FlagDefinition[] = [
  // Transfer
  { name: 'transfers', short: 'T', type: 'int', default: 4, description: 'Number of parallel file transfers.', category: 'Transfer', level: 'basic', placeholder: '4' },
  { name: 'checkers', type: 'int', default: 8, description: 'Number of parallel checkers.', category: 'Transfer', level: 'basic', placeholder: '8' },
  { name: 'max-transfer', type: 'SizeSuffix', description: 'Maximum size of data to transfer.', category: 'Transfer', level: 'advanced', placeholder: 'e.g. 100G' },
  { name: 'max-duration', type: 'Duration', description: 'Maximum duration for transfers.', category: 'Transfer', level: 'advanced', placeholder: 'e.g. 1h' },
  { name: 'max-age', type: 'Duration', description: 'Only transfer files older than this.', category: 'Transfer', level: 'advanced', placeholder: 'e.g. 7d' },
  { name: 'min-age', type: 'Duration', description: 'Only transfer files newer than this.', category: 'Transfer', level: 'advanced', placeholder: 'e.g. 1d' },
  { name: 'multi-thread-cutoff', type: 'SizeSuffix', default: '256M', description: 'Use multi-thread downloads above this size.', category: 'Transfer', level: 'advanced', placeholder: '256M' },
  { name: 'multi-thread-streams', type: 'int', default: 4, description: 'Number of streams for multi-thread downloads.', category: 'Transfer', level: 'advanced', placeholder: '4' },
  { name: 'multi-thread-chunk-size', type: 'SizeSuffix', default: '64M', description: 'Chunk size for multi-thread transfers.', category: 'Transfer', level: 'expert', placeholder: '64M' },
  { name: 'streaming', type: 'int', default: 4, description: 'Number of streams for streaming.', category: 'Transfer', level: 'expert', placeholder: '4' },
  { name: 'buffer-size', type: 'SizeSuffix', default: '16M', description: 'Buffer size per file transfer.', category: 'Transfer', level: 'basic', placeholder: '16M' },
  { name: 'no-traverse', type: 'bool', default: false, description: 'Don\'t traverse the source directory tree.', category: 'Transfer', level: 'advanced' },

  // Bandwidth
  { name: 'bwlimit', type: 'BwTimetable', description: 'Bandwidth limit. Can be a schedule.', category: 'Bandwidth', level: 'basic', placeholder: 'e.g. 10M or "08:00,512k 12:00,10M 18:00,off"' },
  { name: 'bwlimit-file', type: 'BwTimetable', description: 'Bandwidth limit per file.', category: 'Bandwidth', level: 'expert' },

  // Comparison
  { name: 'checksum', short: 'c', type: 'bool', default: false, description: 'Check for changes with size and checksum.', category: 'Comparison', level: 'basic' },
  { name: 'update', short: 'u', type: 'bool', default: false, description: 'Skip files that are newer on the destination.', category: 'Comparison', level: 'basic' },
  { name: 'ignore-times', short: 'I', type: 'bool', default: false, description: 'Transfer all unconditionally (ignore modification times).', category: 'Comparison', level: 'basic' },
  { name: 'size-only', type: 'bool', default: false, description: 'Skip based on size only.', category: 'Comparison', level: 'basic' },
  { name: 'ignore-existing', type: 'bool', default: false, description: 'Skip all files that exist on destination.', category: 'Comparison', level: 'basic' },
  { name: 'no-update-modtime', type: 'bool', default: false, description: 'Don\'t update destination modification time.', category: 'Comparison', level: 'advanced' },
  { name: 'compare-dest', type: 'string', description: 'Additional compare destination for copy.', category: 'Comparison', level: 'expert' },
  { name: 'copy-dest', type: 'string', description: 'Additional copy destination for copy.', category: 'Comparison', level: 'expert' },
  { name: 'immutable', type: 'bool', default: false, description: 'Don\'t modify destination. Fail if file exists.', category: 'Comparison', level: 'advanced' },
  { name: 'checksum-only', type: 'bool', default: false, description: 'Compare by checksum only.', category: 'Comparison', level: 'expert' },
  { name: 'checksum-strict', type: 'bool', default: false, description: 'Use strict checksumming.', category: 'Comparison', level: 'expert' },

  // Sync Behavior
  { name: 'delete-before', type: 'bool', default: false, description: 'Delete on destination before transferring.', category: 'Sync', level: 'basic' },
  { name: 'delete-during', type: 'bool', default: false, description: 'Delete on destination during transfer.', category: 'Sync', level: 'basic' },
  { name: 'delete-after', type: 'bool', default: false, description: 'Delete on destination after transfer (default).', category: 'Sync', level: 'basic' },
  { name: 'delete-excluded', type: 'bool', default: false, description: 'Delete excluded files from destination.', category: 'Sync', level: 'advanced' },
  { name: 'backup-dir', type: 'string', description: 'Move deleted/overwritten files here.', category: 'Sync', level: 'advanced', placeholder: 'remote:path' },
  { name: 'backup-dir-clean-interval', type: 'Duration', description: 'Interval to clean empty backup dirs.', category: 'Sync', level: 'expert' },
  { name: 'backup-dir-max-age', type: 'Duration', description: 'Max age for files in backup dir.', category: 'Sync', level: 'expert' },
  { name: 'track-renames', type: 'bool', default: false, description: 'Track file renames and do server-side moves.', category: 'Sync', level: 'advanced' },
  { name: 'track-renames-suffix', type: 'string', description: 'Suffix to add when tracking renames.', category: 'Sync', level: 'expert' },
  { name: 'suffix', type: 'string', description: 'Suffix to add to changed files.', category: 'Sync', level: 'advanced', placeholder: '.bak' },
  { name: 'fast-list', short: 'F', type: 'bool', default: false, description: 'Use recursive list if available (uses more memory).', category: 'Sync', level: 'basic' },
  { name: 'resync', type: 'bool', default: false, description: 'Resync the bidirectional sync - empty the working directory first (used for bisync first run and recovery).', category: 'Sync', level: 'advanced' },
  { name: 'no-unicode-normalization', type: 'bool', default: false, description: 'Disable unicode normalization.', category: 'Sync', level: 'expert' },

  // Filtering
  { name: 'exclude', type: 'string', description: 'Exclude files matching pattern.', category: 'Filter', level: 'basic', placeholder: '*.tmp' },
  { name: 'include', type: 'string', description: 'Include files matching pattern.', category: 'Filter', level: 'basic', placeholder: '*.jpg' },
  { name: 'filter', type: 'string', description: 'Add a file filtering rule.', category: 'Filter', level: 'advanced', placeholder: '+ *.jpg' },
  { name: 'exclude-from', type: 'string', description: 'Read exclude patterns from file.', category: 'Filter', level: 'basic', placeholder: 'path/to/excludes.txt' },
  { name: 'include-from', type: 'string', description: 'Read include patterns from file.', category: 'Filter', level: 'advanced', placeholder: 'path/to/includes.txt' },
  { name: 'filter-from', type: 'string', description: 'Read filter patterns from file.', category: 'Filter', level: 'advanced', placeholder: 'path/to/filters.txt' },
  { name: 'min-size', type: 'SizeSuffix', description: 'Minimum file size to transfer.', category: 'Filter', level: 'basic', placeholder: 'e.g. 100M' },
  { name: 'max-size', type: 'SizeSuffix', description: 'Maximum file size to transfer.', category: 'Filter', level: 'basic', placeholder: 'e.g. 1G' },
  { name: 'max-age', type: 'Duration', description: 'Maximum age of files to transfer.', category: 'Filter', level: 'basic', placeholder: 'e.g. 30d' },
  { name: 'min-age', type: 'Duration', description: 'Minimum age of files to transfer.', category: 'Filter', level: 'basic', placeholder: 'e.g. 1d' },

  // Logging
  { name: 'log-file', type: 'string', description: 'Log everything to this file.', category: 'Logging', level: 'basic', placeholder: 'path/to/logfile.log' },
  { name: 'log-file-max-size', type: 'SizeSuffix', default: '100M', description: 'Maximum size of log file.', category: 'Logging', level: 'advanced', placeholder: '100M' },
  { name: 'log-level', type: 'string', default: 'NOTICE', description: 'Log level.', category: 'Logging', level: 'basic', placeholder: 'DEBUG|INFO|NOTICE|WARNING|ERROR' },
  { name: 'stats', type: 'Duration', default: '1m', description: 'Interval between stats output.', category: 'Logging', level: 'basic', placeholder: '30s' },
  { name: 'stats-one-line', type: 'bool', default: false, description: 'Compact single-line stats output.', category: 'Logging', level: 'basic' },
  { name: 'stats-one-line-date', type: 'bool', default: false, description: 'Add date/time to single-line stats.', category: 'Logging', level: 'advanced' },
  { name: 'stats-log-level', type: 'string', default: 'INFO', description: 'Log level for stats.', category: 'Logging', level: 'advanced' },
  { name: 'use-json-log', type: 'bool', default: false, description: 'Use JSON log output.', category: 'Logging', level: 'advanced' },
  { name: 'quiet', short: 'q', type: 'bool', default: false, description: 'Print as little as possible.', category: 'Logging', level: 'basic' },
  { name: 'verbose', short: 'v', type: 'bool', default: false, description: 'Print lots more stuff.', category: 'Logging', level: 'basic' },
  { name: 'progress', short: 'P', type: 'bool', default: false, description: 'Show progress during transfer.', category: 'Logging', level: 'basic' },
  { name: 'progress-terminal-title', type: 'bool', default: false, description: 'Show progress in terminal title.', category: 'Logging', level: 'advanced' },
  { name: 'dry-run', short: 'n', type: 'bool', default: false, description: 'Do a trial run with no permanent changes.', category: 'Logging', level: 'basic' },
  { name: 'color', type: 'string', default: 'AUTO', description: 'When to show colors (AUTO/NEVER/ALWAYS).', category: 'Logging', level: 'basic', placeholder: 'AUTO|NEVER|ALWAYS' },

  // Error Handling
  { name: 'max-retries', type: 'int', default: 3, description: 'Max number of retries.', category: 'Error Handling', level: 'basic', placeholder: '3' },
  { name: 'low-level-retries', type: 'int', default: 10, description: 'Max number of low-level retries.', category: 'Error Handling', level: 'advanced', placeholder: '10' },
  { name: 'retries-sleep', type: 'Duration', description: 'Sleep time between retries.', category: 'Error Handling', level: 'advanced', placeholder: 'e.g. 10s' },
  { name: 'retry-on-timeout', type: 'bool', default: false, description: 'Retry on timeout.', category: 'Error Handling', level: 'expert' },
  { name: 'retry-on-500', type: 'bool', default: false, description: 'Retry on HTTP 500 errors.', category: 'Error Handling', level: 'expert' },
  { name: 'retry-on-snapshot-delete', type: 'bool', default: false, description: 'Retry on snapshot deletion errors.', category: 'Error Handling', level: 'expert' },

  // Networking
  { name: 'timeout', type: 'Duration', default: '5m', description: 'IO idle timeout.', category: 'Network', level: 'basic', placeholder: '5m' },
  { name: 'connect-timeout', type: 'Duration', default: '1m', description: 'Connect timeout.', category: 'Network', level: 'advanced', placeholder: '1m' },
  { name: 'dscp', type: 'string', description: 'DSCP value for QoS.', category: 'Network', level: 'expert' },
  { name: 'disable-http-keep-alives', type: 'bool', default: false, description: 'Disable HTTP keep-alives.', category: 'Network', level: 'expert' },
  { name: 'disable-http2', type: 'bool', default: false, description: 'Disable HTTP/2.', category: 'Network', level: 'expert' },
  { name: 'http-addr', type: 'string', description: 'HTTP address for incoming connections.', category: 'Network', level: 'expert' },
  { name: 'http-proxy', type: 'string', description: 'HTTP proxy server.', category: 'Network', level: 'advanced', placeholder: 'http://proxy:8080' },
  { name: 'no-check-certificates', type: 'bool', default: false, description: 'Don\'t verify SSL certificates.', category: 'Network', level: 'advanced' },
  { name: 'user-agent', type: 'string', description: 'User-agent string.', category: 'Network', level: 'expert' },

  // Performance
  { name: 'cache-dir', type: 'string', description: 'Directory for cache files.', category: 'Performance', level: 'advanced', placeholder: '~/.cache/rclone' },
  { name: 'chunked-reading', type: 'SizeSuffix', default: '128K', description: 'Chunk size for reading.', category: 'Performance', level: 'expert' },
  { name: 'no-cache', type: 'bool', default: false, description: 'Disable the filesystem cache.', category: 'Performance', level: 'expert' },
  { name: 'no-update-ctime', type: 'bool', default: false, description: 'Don\'t update ctime.', category: 'Performance', level: 'expert' },
  { name: 'read-memory-limit', type: 'SizeSuffix', default: '128M', description: 'Memory limit for reading.', category: 'Performance', level: 'expert' },
  { name: 'write-back-cache', type: 'bool', default: false, description: 'Use write-back cache.', category: 'Performance', level: 'expert' },

  // Metadata
  { name: 'metadata', short: 'M', type: 'bool', default: false, description: 'Preserve metadata when copying.', category: 'Metadata', level: 'advanced' },
  { name: 'metadata-set', type: 'string', description: 'Set metadata key=value.', category: 'Metadata', level: 'expert', placeholder: 'key=value' },

  // Advanced
  { name: 'config', type: 'string', description: 'Config file location.', category: 'Advanced', level: 'advanced', placeholder: 'path/to/rclone.conf' },
  { name: 'temp-dir', type: 'string', description: 'Temporary directory.', category: 'Advanced', level: 'advanced', placeholder: '~/.cache/rclone/tmp' },
  { name: 'cache-chunk-missing-age', type: 'Duration', description: 'Max age of missing chunks.', category: 'Advanced', level: 'expert' },
  { name: 'cache-dir', type: 'string', description: 'Cache directory.', category: 'Advanced', level: 'advanced', placeholder: '~/.cache/rclone' },
  { name: 'no-checksum', type: 'bool', default: false, description: 'Don\'t checksum.', category: 'Advanced', level: 'expert' },
  { name: 'no-gzip-encoding', type: 'bool', default: false, description: 'Don\'t gzip encoding.', category: 'Advanced', level: 'expert' },
  { name: 'no-update-dir-ctime', type: 'bool', default: false, description: 'Don\'t update dir ctime.', category: 'Advanced', level: 'expert' },
  { name: 'use-server-modtime', type: 'bool', default: false, description: 'Use server modification time.', category: 'Advanced', level: 'advanced' },
  { name: 'convert', type: 'bool', default: false, description: 'Convert file names.', category: 'Advanced', level: 'expert' },
  { name: 'convert-flags', type: 'string', description: 'Convert flags.', category: 'Advanced', level: 'expert' },
  { name: 'fs-cache', type: 'Duration', default: '5m', description: 'FS cache duration.', category: 'Advanced', level: 'expert' },
  { name: 'rc-addr', type: 'string', default: 'localhost:5572', description: 'RC API listen address.', category: 'Advanced', level: 'advanced', placeholder: 'localhost:5572' },
  { name: 'rc-user', type: 'string', default: '', description: 'RC API username.', category: 'Advanced', level: 'advanced' },
  { name: 'rc-pass', type: 'string', default: '', description: 'RC API password.', category: 'Advanced', level: 'advanced' },
  { name: 'rc-no-auth', type: 'bool', default: false, description: 'Disable RC API authentication.', category: 'Advanced', level: 'expert' },
  { name: 'human-readable', type: 'bool', default: false, description: 'Human-readable sizes.', category: 'Advanced', level: 'basic' },
  { name: 'metadata-mapper', type: 'string', description: 'Program to transform metadata.', category: 'Advanced', level: 'expert' },
  { name: 'server-side-across-configs', type: 'bool', default: false, description: 'Allow server-side operations across configs.', category: 'Advanced', level: 'expert' },
  { name: 'skip-links', type: 'bool', default: false, description: 'Skip symlinks.', category: 'Advanced', level: 'advanced' },
  { name: 'skip-symlinks', type: 'bool', default: false, description: 'Skip symlinks (alias).', category: 'Advanced', level: 'expert' },
  { name: 'stats-file-name-length', type: 'int', default: 40, description: 'Max length of stats file name.', category: 'Advanced', level: 'expert' },
  { name: 'stats-reset', type: 'Duration', description: 'Reset stats after interval.', category: 'Advanced', level: 'expert' },
  { name: 'stats-two-way', type: 'bool', default: false, description: 'Two-way stats.', category: 'Advanced', level: 'expert' },
  { name: 'terminal-fd', type: 'string', description: 'Terminal file descriptor.', category: 'Advanced', level: 'expert' },
  { name: 'tpslimit', type: 'int', default: 0, description: 'HTTP transactions per second limit.', category: 'Advanced', level: 'expert' },
  { name: 'tpslimit-burst', type: 'int', default: 1, description: 'HTTP TPS burst limit.', category: 'Advanced', level: 'expert' },
  { name: 'order-by', type: 'string', description: 'Order transfers by.', category: 'Advanced', level: 'advanced', placeholder: 'size,modtime,name' },
  { name: 'no-unicode-normalization', type: 'bool', default: false, description: 'Disable unicode normalization.', category: 'Advanced', level: 'expert' },
  { name: 'no-console-log', type: 'bool', default: false, description: 'Disable console logging.', category: 'Advanced', level: 'expert' }
]
